services:
  discovery-service:
    image: elboukhariyoucef/discoveryservice:1.0.0
    container_name: discovery-service-container
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD","curl","f","http://localhost:8761/actuator/health"]
      interval: 10s
  config-service:
    image: elboukhariyoucef/configservice:1.0.0
    container_name: config-service-container
    ports:
      - "9999:9999"
    expose:
      - "9999"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka
    healthcheck:
      test: [ "CMD","curl","f","http://localhost:9999/actuator/health" ]
      interval: 10s
    depends_on:
      discovery-service:
        condition: service_healthy

  customer-service:
    image: elboukhariyoucef/customerservice:1.0.0
    container_name: customer-service-container
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service-container:9999
    healthcheck:
      test: [ "CMD","curl","f","http://localhost:8081/actuator/health" ]
      interval: 30s
    depends_on:
      config-service:
        condition: service_healthy

  account-service:
    image: elboukhariyoucef/accountservice:1.0.0
    container_name: account-service-container
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service-container:9999
    depends_on:
      customer-service:
        condition: service_healthy

  gateway-service:
    image: elboukhariyoucef/gatewayservice:1.0.0
    container_name: gateway-service-container
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service-container:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service-container:9999
    depends_on:
      config-service:
        condition: service_healthy

  front-end-angular:
    build: angular-front-end
    container_name: front-end-angular
    ports:
      - "80:80"
    expose:
      - "80"




